# Generated by Django 3.2.13 on 2025-11-11 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entry_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelapp',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='acco.accountsuser'),
            preserve_default=False,
        ),
    ]
